import type { Metadata } from 'next'
import { Roboto} from 'next/font/google'
import './globals.css'
import AsideComponent from '@/components/AsideComponent'
import Providers from '@/tools/Providers'
import icon from '../../public/icon.png'

const inter = Roboto({ 
  subsets: ['latin'], 
  weight: ['300','400','500','700']
})

export const metadata: Metadata = {
  title: 'Dashboard Bash',
  description: 'Generated by create next app',
  icons: `${icon}`
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={inter.className}>
          <body className='relative'>
            <Providers>
              <AsideComponent />
              {children}
            </Providers>
          </body>
    </html>
  )
}
